### PR TITLE
Update text.js

### PR DESCRIPTION
**Pull request by wesleimp**

### CODE REVIEW

**Comment by Patricia7sp** [comment]
Ola pessoal boa tarde!

Desculpe estar publicando meu assunto aqui e que nao consegui abrir um novo pull.  
estou com um problema, estou com um erro  com relacao a content.
Nao estou conseguindo achar a falha, porque diz que ja foi declarada o content.


(node:26670) UnhandledPromiseRejectionWarning: SyntaxError: Identifier 'content' has already been declared
    at start (/home/patricia/rob-s-maker/index.js:9:16)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:51:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:804:11)
    at internal/main/run_main_module.js:21:11
(node:26670) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26670) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


Agradeco a atencao de todos.

**Comment by cabral-ricardo** [comment]
@Patricia7sp Verifica se no arquivo index.js na linha se você retirou o context do parametro ``` await robots.text();```

**Comment by leodutra** [comment]
> Identifier 'content' has already been declared
Está declarando duas vezes content

**Comment by yurimedeiros** [comment]
(node:16488) UnhandledPromiseRejectionWarning: authorization required
(node:16488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
 error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). (rejectio
n id: 1)
(node:16488) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr
ecated. In the future, promise rejections that are not handled will terminate th
e Node.js process with a non-zero exit code.


=======

ESTOU COM ESTE ERRO ME AJUDA POR FAVOR

**Comment by geeklicantropo** [comment]
> Ola pessoal boa tarde!
> 
> Desculpe estar publicando meu assunto aqui e que nao consegui abrir um novo pull.
> estou com um problema, estou com um erro com relacao a content.
> Nao estou conseguindo achar a falha, porque diz que ja foi declarada o content.
> 
> (node:26670) UnhandledPromiseRejectionWarning: SyntaxError: Identifier 'content' has already been declared
> at start (/home/patricia/rob-s-maker/index.js:9:16)
> at processTicksAndRejections (internal/process/next_tick.js:81:5)
> at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:51:3)
> at Function.Module.runMain (internal/modules/cjs/loader.js:804:11)
> at internal/main/run_main_module.js:21:11
> (node:26670) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:26670) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 
> Agradeco a atencao de todos.

Eu possuo exatamente o mesmo problema. Sei que a variável content deve estar replicada em algum lugar, mas se tu olhar o código atual no github, ele também está replicado e no entanto, parece que não está dando problema para mais ninguém.

**Comment by MatheusRV** [comment]
O que exatamente esse PR está realizando?

**Pull request closed without merging**
